[package]
name = "graphics_tester"
version = "0.1.0"
edition = "2021"
authors = ["Emma Britton <emmabritton@pm.me>"]
readme = "README.md"
license-file = "LICENSE"
description = "Graphics tester"
publish = false

[dependencies]
pixels-graphics-lib = "0.14.2"
anyhow = "1.0.76"